/**
 * Pomodoro notifications via notifee (native — needs a dev build / APK, not
 * Expo Go).
 *
 *  - Ongoing notification uses Android's native chronometer, so the countdown
 *    keeps ticking even when the app is backgrounded or killed (no JS running).
 *  - A full-screen alarm is scheduled (AlarmManager) at the phase end, so it
 *    fires — with sound + a full-screen intent that surfaces the app — even if
 *    the app is closed, just like a clock alarm.
 *
 * Lazy-required and feature-flagged: in Expo Go (where the native module is
 * absent) every call is a no-op, so the in-app overlay + chime still work.
 */
import { Platform } from "react-native";
import Constants, { ExecutionEnvironment } from "expo-constants";

const ONGOING_ID = "focus-ongoing";
const ALARM_ID = "focus-alarm";
const TIMER_CHANNEL = "focus-timer";
const ALARM_CHANNEL = "focus-alarm";
const SMALL_ICON = "notification_icon"; // generated by the expo-notifications plugin
const BRAND = "#272d29";

const inExpoGo =
  Constants.executionEnvironment === ExecutionEnvironment.StoreClient;

/* eslint-disable @typescript-eslint/no-explicit-any */
let notifee: any = null;
let A: any = {};
if (!inExpoGo && Platform.OS !== "web") {
  try {
    const n = require("@notifee/react-native");
    notifee = n.default;
    A = n;
    // A no-op background handler keeps notifee from warning when a notification
    // is delivered while the app is in the background.
    notifee.onBackgroundEvent(async () => {});
  } catch {
    notifee = null;
  }
}

let configured = false;

/** Request permission + create the timer/alarm channels. Safe to repeat. */
export async function configureNotifications(): Promise<void> {
  if (configured || !notifee) return;
  configured = true;
  try {
    await notifee.requestPermission();
    if (Platform.OS === "android") {
      await notifee.createChannel({
        id: TIMER_CHANNEL,
        name: "Focus timer",
        importance: A.AndroidImportance.LOW,
        vibration: false,
      });
      await notifee.createChannel({
        id: ALARM_CHANNEL,
        name: "Focus alarm",
        importance: A.AndroidImportance.HIGH,
        sound: "default",
        vibration: true,
        vibrationPattern: [300, 400, 300, 400],
      });
    }
  } catch {
    /* notifications are best-effort */
  }
}

/**
 * Show / update the ongoing countdown. While running it uses the native
 * chronometer (ticks even with the app closed); while paused it shows a frozen
 * "Paused · mm:ss".
 */
export async function showOngoing(opts: {
  title: string;
  endAt: number;
  paused: boolean;
  remainingMs?: number;
}): Promise<void> {
  if (!notifee) return;
  try {
    const mmss = (ms: number) =>
      `${Math.floor(ms / 60_000)}:${String(Math.floor((ms % 60_000) / 1000)).padStart(2, "0")}`;
    await notifee.displayNotification({
      id: ONGOING_ID,
      title: opts.title,
      body: opts.paused ? `Paused · ${mmss(opts.remainingMs ?? 0)}` : undefined,
      android: {
        channelId: TIMER_CHANNEL,
        smallIcon: SMALL_ICON,
        color: BRAND,
        ongoing: true,
        onlyAlertOnce: true,
        autoCancel: false,
        showChronometer: !opts.paused,
        chronometerDirection: "down",
        timestamp: opts.paused ? undefined : opts.endAt,
        pressAction: { id: "default", launchActivity: "default" },
      },
    });
  } catch {
    /* no-op */
  }
}

export async function clearOngoing(): Promise<void> {
  if (!notifee) return;
  try {
    await notifee.cancelNotification(ONGOING_ID);
  } catch {
    /* no-op */
  }
}

/** Schedule the end-of-phase alarm (fires via AlarmManager even if app closed). */
export async function scheduleAlarm(
  endAt: number,
  title: string,
  body: string,
): Promise<void> {
  if (!notifee) return;
  try {
    await notifee.cancelTriggerNotification(ALARM_ID);
    if (endAt <= Date.now() + 500) return;
    await notifee.createTriggerNotification(
      {
        id: ALARM_ID,
        title,
        body,
        android: {
          channelId: ALARM_CHANNEL,
          smallIcon: SMALL_ICON,
          color: BRAND,
          category: A.AndroidCategory.ALARM,
          importance: A.AndroidImportance.HIGH,
          visibility: A.AndroidVisibility.PUBLIC,
          pressAction: { id: "default", launchActivity: "default" },
          // Surface the app full-screen, like a clock alarm.
          fullScreenAction: { id: "default", launchActivity: "default" },
        },
      },
      {
        type: A.TriggerType.TIMESTAMP,
        timestamp: endAt,
        alarmManager: { allowWhileIdle: true },
      },
    );
  } catch {
    /* no-op */
  }
}

export async function cancelAlarm(): Promise<void> {
  if (!notifee) return;
  try {
    await notifee.cancelTriggerNotification(ALARM_ID);
    await notifee.cancelNotification(ALARM_ID);
  } catch {
    /* no-op */
  }
}
